### ISSUE TITLE
commit message 类型为fix或者其他的时候，回显还是feat

### ISSUE THREAD

**Issue by destinym** [yumchina/infrared_issues#2]
### 版本
v0.5

### 现象
如下图所示，commit message 内容为fix, 但是回显之后为feat.
![image](https://user-images.githubusercontent.com/3216650/187877001-ffe33cf2-26cc-4de5-a9f6-66a5dc0fd475.png)

### 问题
这样导致，修改bug类型的描述的时候，每次都要选择一下提交类型。

**Comment by yumchina** [comment]
fixed in v0.6.
