### ISSUE TITLE
idea版本问题

### ISSUE THREAD

**Issue by wangjiazhan** [yumchina/infrared_issues#3]
**问题版本:**
v0.6

**问题描述：**
版本：idea 2019.2.4
目前在该版本上安装插件会出现兼容性问题，是否需要升级到最新版本才可以使用
问题如下图所示：
![image](https://user-images.githubusercontent.com/87747648/188053572-87b8797c-b655-4c62-ae74-c6fb95eda09a.png)

**Comment by yumchina** [comment]
由于API兼容性问题，只支持Jetbrains 2020之后的所有版本(2020.1.1 +)。2019短期不会支持。
